export const PROMPTS = {
  ANIME: [
    'GOKU', 'NARUTO', 'GOJO', 'ITACHI', 'LUFFY', 'EREN', 'TANJIRO', 'ZENITSU', 'VEGETA', 'SASUKE',
    'SAITAMA', 'LIGHT_YAGAMI', 'LEVI', 'ZORO', 'SUKUNA', 'DEKU', 'BAKUGO', 'KILLUA', 'GON', 'KANEKI',
    'ICHIGO', 'EDWARD_ELRIC', 'NEZUKO', 'RIMURU', 'CHIIRO', 'AOT_COLOSSAL', 'SHANKS', 'KAKASHI', 'MADARA', 'HISOKA',
    'ALUCARD', 'AOT_MIKASA', 'ARMIN', 'ASUKA', 'AYANOKOJI', 'BAN_7DS', 'BEERUS', 'BLACK_BEARD', 'BORYTO', 'BULMA',
    'CHOPPER', 'DEATH_NOTE_RYUK', 'DENJI', 'DIOR', 'DOFLAMINGO', 'DR_STONE', 'ERZA', 'FUSHIGURO', 'GARA', 'GINTOKI',
    'GOHAN', 'GRIFFITH', 'GUTTS', 'HAJIME_NO_IPPO', 'INOSUKE', 'INOYASHA', 'ISAGI', 'ITADORI', 'JIREN', 'JUVO',
    'KAGUYA', 'KAMADO', 'KAYABA', 'KENSHIN', 'KIRA', 'KIRITO', 'KURAPIKA', 'KURAMA', 'KUSHINA', 'LAW_ONE_PIECE',
    'MAKIMA', 'MELIODAS', 'MINATO', 'MOB_PSYCHO', 'MHA_ALL_MIGHT', 'NAGATO', 'Natsu', 'OBITO', 'PAIN_NARUTO', 'POWER_CHAINSAW',
    'REIGEN', 'REI_AYANAMI', 'REROUCH', 'RIN_TOHSAKA', 'ROB_LUCCI', 'ROY_MUSTANG', 'RYUK', 'SABO', 'SAKURA', 'SANJI',
    'SENKU', 'SHIGARAKI', 'SHINJI_IKARI', 'SOKA', 'SORA_KH', 'SOSUKE_AIZEN', 'TOJI_FUSHIGURO', 'TSUNADE', 'USOPP', 'ZELEPH'
  ],

  CARTOON: [
    'SPONGEBOB', 'SHREK', 'MINION', 'TOM', 'JERRY', 'BEN10', 'OGGY', 'POPEYE', 'DORAEMON', 'PATRICK',
    'SQUIDWARD', 'SCOOBY_DOO', 'SHAGGY', 'BUGS_BUNNY', 'DAFFY_DUCK', 'MICKEY_MOUSE', 'DONALD_DUCK', 'SIMBA', 'POOH_BEAR', 'STITCH',
    'PIKACHU', 'FINN', 'JAKE', 'MORDECAI', 'RIGBY', 'GUMBALL', 'COWARDLY_DOG', 'PHINEAS', 'FERB', 'HOMER_SIMPSON',
    'ALADDIN', 'ANG', 'ANAKIN_CHIBI', 'ARCHIE', 'ARTICUNO', 'ASH_KETCHUM', 'ASTERIX', 'BART_SIMPSON', 'BATMAN_TAS', 'BLOSSOM_PUP',
    'BAMBI', 'BARNEY', 'BOB_BURGER', 'BOJACK', 'BRAIN_PINKY', 'BUBBLES_PUP', 'BUTTERCUP_PUP', 'CAT_AND_DOG', 'CHARLIE_BROWN', 'COSMO',
    'COURAGE_DOG', 'DEXTER_LAB', 'DIDI', 'DONATELLO', 'DORA_EXPLORER', 'ELMO', 'ELSA', 'FRED_FLINTSTONE', 'GARFIELD', 'GOOFY',
    'GRINCH', 'HE_MAN', 'INSPECTOR_GADGET', 'JIMMY_NEUTRON', 'JOHNNY_BRAVO', 'KIM_POSSIBLE', 'KRUSTY_KRAB', 'LEONARDO_TMNT', 'LISA_SIMPSON', 'MOANA',
    'MUGMAN', 'MICHELANGELO', 'MINNIE_MOUSE', 'MR_BEAN', 'MUTTLEY', 'NIGEL_THORNBERRY', 'OLAF', 'OPTIMUS_PRIME', 'PADDINGTON', 'PESTER_PAN',
    'PETER_GRIFFIN', 'PLANKTON', 'PLUTO_DOG', 'RAPHAEL_TMNT', 'RICK_SANCHEZ', 'ROBO_COP_ANIMATED', 'SAMURAI_JACK', 'SNOOPY', 'SPEED_RACER', 'STEWIE_GRIFFIN',
    'TARZAN', 'TAZ_DEVIL', 'TIMMY_TURNER', 'TWEETY_BIRD', 'UNDERDOG', 'WANDA', 'WENNIE_POOH', 'WOODY_TOY_STORY', 'YOGI_BEAR', 'ZIM'
  ],

  GAMING: [
    'MARIO', 'SONIC', 'KRATOS', 'LINK', 'STEVE', 'LUIGI', 'PACMAN', 'MASTER_CHIEF', 'DONKEY_KONG', 'MEGA_MAN',
    'BOWSER', 'PRINCESS_PEACH', 'CHIEF_PIRATE', 'SANS', 'ALOY', 'GERALT', 'ARTHUR_MORGAN', 'CJ_GTA', 'PETER_PARKER', 'SPYRO',
    'CRASH_BANDICOOT', 'DOOM_SLAYER', 'SAMUS', 'SEPHIROTH', 'CLOUD_STRIFE', 'AGENT_47', 'TRAVIS_SCOTT', 'CREEPER', 'ENDERMAN', 'CHUN_LI',
    'ALUCARD_CASTLE', 'AMONG_US_IMPOSTOR', 'ASHE_OVERWATCH', 'BALLAS_GTA', 'BANJO_KAZOOIE', 'BASTION', 'BLASTOISE', 'CANDY_CRUSH', 'CAPTAIN_PRICE', 'CHARIZARD',
    'CHOCABO', 'CIRI', 'COLE_PHELPS', 'CORVO', 'CYNDER', 'DANTE_DMC', 'DARK_SOULS_KNIGHT', 'DEATHWING', 'DECKARD_CAIN', 'DIABLO',
    'DR_EGGMAN', 'DUKE_NUKEM', 'ELLIE_TLOU', 'EZIO_AUDITORE', 'FOLLOUT_BOY', 'FOX_MCCLOUD', 'FRANK_FRANKLIN', 'GORDON_FREEMAN', 'GOUKI', 'GUY_BRUSH',
    'GYRADOS', 'ILLIDAN', 'JAGO', 'JIN_KAZAMA', 'JOHNNY_SILVERHAND', 'KASSANDRA', 'KAZUYA', 'KIRBY', 'LARA_CROFT', 'LEON_KENNEDY',
    'LI_MEI', 'LIQUID_SNAKE', 'MARCUS_FENIX', 'MAX_PAYNE', 'MEWTWO', 'MINECRAFT_ALEX', 'NATHAN_DRAKE', 'NIKO_BELLIC', 'PAC_GHOST', 'PAGAN_MIN',
    'PARAPPA', 'PROPHET_CRYSIS', 'PYRAMID_HEAD', 'RAYMAN', 'REPTILE_MK', 'RYU_SF', 'SACKBOY', 'SCORPION_MK', 'SHODAN', 'SOLID_SNAKE',
    'SUB_ZERO', 'THRILL', 'TREVOR_GTA', 'TYRAEL', 'V_CYBERPUNK', 'VAAS', 'VENOM_SNAKE', 'WARCRAFT_ARTHAS', 'YOSHI', 'ZELDA'
  ],

  RANDOM: [
    'ROBOT', 'AIRPLANE', 'VOLCANO', 'ASTRONAUT', 'ELEPHANT', 'TRACTOR', 'CASTLE', 'DRAGON', 'PIZZA', 'PIRATE',
    'BURGER', 'SUBMARINE', 'DINOSAUR', 'SHARK', 'SPACESHIP', 'SKYSCRAPER', 'DIAMOND', 'TREASURE_CHEST', 'NINJA', 'WIZARD',
    'ALIEN', 'EGYPT_PYRAMID', 'LIGHTHOUSE', 'ROLLER_COASTER', 'HELICOPTER', 'PHOENIX', 'UNICORN', 'HOT_AIR_BALLOON', 'CAMPFIRE', 'SPIDER_WEB',
    'ANCHOR', 'ANVIL', 'AVOCADO', 'AXE', 'BACKPACK', 'BANANA', 'BARN', 'BATTERY', 'BICYCLE', 'BLENDER',
    'BONFIRE', 'BOW_AND_ARROW', 'BRIDGE', 'BROOM', 'CACTUS', 'CAMERA', 'CANDLE', 'CANNON', 'CAROUSEL', 'CHEF_HAT',
    'CHESS_KNIGHT', 'COFFEE_MUG', 'COMPASS', 'COWBOY_BOOTS', 'CROWN', 'CRUISE_SHIP', 'DONUT', 'DRUM_SET', 'EIFFEL_TOWER', 'FERRIS_WHEEL',
    'FIRE_HYDRANT', 'FIRE_TRUCK', 'FLAMINGO', 'FLASHLIGHT', 'FOUNTAIN', 'GECKO', 'GLOBE', 'GOLF_CLUB', 'GUITAR', 'HAMMER',
    'HOT_DOG', 'HOURGLASS', 'ICE_CREAM', 'IGLOO', 'KEYBOARD', 'KITE', 'LANTERN', 'LEMON', 'LION', 'MAGNET',
    'MICROSCOPE', 'MIRROR', 'MOTORCYCLE', 'MUSHROOM', 'OWL', 'PARACHUTE', 'PENGUIN', 'PIANO', 'PUMPKIN', 'RADIO',
    'ROCKET', 'SANDCASTLE', 'SCISSORS', 'SKATEBOARD', 'SNOWMAN', 'STATUE_OF_LIBERTY', 'SUNFLOWER', 'TELESCOPE', 'TENT', 'WINDMILL'
  ],
} as const;

export type PromptTheme = keyof typeof PROMPTS;